import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import HeroCard from '../components/HeroCard'
import styles from '../styles/Home.module.css'
import useAuthContext from '../utils/useAuthContext'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Screen List</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeroCard/>
		</div>
	)
}
